{{alias}}
skipdomain = -block
proxy = -filter{skipdomain} +forward-override{forward-socks5 192.168.1.212:1080 .}

{skipdomain}
pwd.soulogic.com
.pwd.soulogic.com

{proxy}
.duckduckgo.com
.google.com
.google.co.hk
.soulogic.com
.youtube.com
.googlevideo.com
.ytimg.com
.facebook.com
.imgur.com
.twitter.com
.blogspot.com
.fbcdn.net
.appspot.com
.chinagfw.org
.blogger.com
.googleapis.com
.googleusercontent.com
.mail.google.com
.admin.google.com
.xys.org
.nytimes.com
.img.ly
.fc2.com
.thepiratebay.org
.thepiratebay.se
.bit.ly
.dropbox.com
.gstatic.com
.t.co
.youtu.be
.plus.google.com
.feedproxy.google.com
.feeds.feedburner.com
.feedburner.google.com
.drive.google.com
.picasaweb.google.com
.wordpress.com
.wp.me
.wpcomwidgets.com
.player.vimeo.com
.slideshare.net
.calameo.com
.mitbbs.com
.gamer.com.tw
.eveonline.com
#.jp
#.gungho.jp
.fc2.com
.pornhub.com
.eyny.com
.openbittorrent.com
.publicbt.com
.istole.it
.demonii.com
.publicbt.com
.prq.to
.h3q.com
.openbittorrent.com
.shadowsocks.org
