module.exports = {
	plugins: ['@typescript-eslint/eslint-plugin'],
	parser: '@typescript-eslint/parser',
	extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
	parserOptions: {
		ecmaVersion: 2019,
		sourceType: 'module',
		ecmaFeatures: {
			impliedStrict: true,
		},
	},
	env: {
		es6: true,
		node: true,
		browser: true,
	},
	rules: {
		quotes: ['error', 'single'],
		semi: 'error',
		indent: ['error', 'tab', {
			SwitchCase: 1,
			outerIIFEBody: 1,
			MemberExpression: 1,
		}],
		curly: 'error',
		'@typescript-eslint/explicit-function-return-type': 'off',
		'no-unused-expressions': ['error', { 'allowShortCircuit': true }],
		'no-unneeded-ternary': 'error',
		'array-bracket-spacing': ['error', 'never'],
		'arrow-spacing': 'error',
		'block-spacing': 'error',
		'comma-dangle': ['error', 'always-multiline'],
		'comma-spacing': ['error', { before: false, after: true }],
		'comma-style': 'error',
		'func-call-spacing': ['error', 'never'],
		'brace-style': ['error', '1tbs', { 'allowSingleLine': false }],
		'key-spacing': 'error',
		'keyword-spacing': 'error',
		'no-constant-condition': 'off',
		'no-empty': ['error', { allowEmptyCatch: true }],
		'no-empty-function': ['error', { 'allow': ['constructors'] }],
		'no-multi-spaces': 'error',
		'no-unused-vars': ['warn', { varsIgnorePattern: '_', args: 'none' }],
		'no-var': 'error',
		'object-curly-spacing': ['error', 'always'],
		'prefer-arrow-callback': 'error',
		'prefer-const': 'error',
		'quote-props': ['error', 'as-needed'],
		'space-in-parens': 'error',
		'space-infix-ops': ['error', { int32Hint: false }],
		'space-before-blocks': 'error',
	},
};
