#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = fcitx5 -d
exec-once = waybar
exec-once = elephant
exec-once = hypridle

exec-once = systemctl --user start polkit-gnome-authentication-agent-1

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = ~/conf/hypr/script/start-wezterm.sh
# exec-once = ~/conf/hypr/script/kvm-win11.sh
# exec-once = ~/conf/hypr/script/start-qq.sh
exec-once = ~/conf/hypr/script/init-chrome-default.sh
# exec-once = ~/conf/hypr/script/chrome-pad.sh

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY
