################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto
#monitor = Virtual-1, 3840x2160@60.00, 0x0, 2
monitor = HDMI-A-1, 3840x2160@120.00, 0x0, 2
monitor = DP-1, 3840x2160@120.00, 0x1080, 2

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = wezterm
$fileManager = nautilus
$menu = wofi --show drun

workspace = name:qq, monitor:DP-1, default:true
workspace = name:chrome-default, monitor:DP-1, default:true
workspace = name:chrome-pad, monitor:DP-1, default:true
workspace = name:chrome-office, monitor:DP-1, default:true
workspace = name:wezterm, monitor:DP-1, default:true
workspace = name:win11, monitor:HDMI-A-1, default:true
workspace = name:log, monitor:HDMI-A-1, default:true
workspace = name:devtools, monitor:HDMI-A-1, default:true
workspace = name:tmu, monitor:HDMI-A-1, default:true
