################
### MONITORS ###
################

$m1 = HDMI-A-1
$m2 = DP-1

# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto
#monitor = Virtual-1, 3840x2160@60.00, 0x0, 2
monitor = $m1, 3840x2160@120.00, 0x0, 2
monitor = $m2, 3840x2160@120.00, 0x1080, 2

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = wezterm
$fileManager = nautilus
$menu = walker

workspace = name:qq, monitor:$m2, default:true
workspace = name:chrome-default, monitor:$m2, default:true
workspace = name:chrome-pad, monitor:$m2, default:true
workspace = name:chrome-office, monitor:$m2, default:true
workspace = name:wezterm, monitor:$m2, default:true

workspace = name:win11, monitor:$m1, default:true
workspace = name:log, monitor:$m1, default:true
workspace = name:devtools, monitor:$m1, default:true
workspace = name:tmu, monitor:$m1, default:true
