################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto
#monitor = Virtual-1, 3840x2160@60.00, 0x0, 2
monitor = DP-4, 3840x2160@60.00, 0x0, 2
monitor = HDMI-A-5, 3840x2160@60.00, 0x0, 2

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = wezterm
$fileManager = nautilus
$menu = wofi --show drun
