exec-once = fcitx5 -d
exec-once = waybar
exec-once = ~/conf/hypr/script/start-wezterm.sh
exec-once = ~/conf/hypr/script/kvm-win11.sh
exec-once = ~/conf/hypr/script/start-qq.sh

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY
