env = HYPRSHOT_DIR, $HOME/Pictures

ecosystem {
    enforce_permissions = true
}

permission = /usr/bin/grim, screencopy, allow

windowrule = match:class satty, float on
windowrule = match:class ^satty$, maximize off
windowrule = match:class com.gabm.satty, float on
windowrule = match:class com.gabm.satty, fullscreen on
# windowrule = match:class com.gabm.satty, size 800 600

# bind = , Print, exec, grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
bindl = ALT, PRINT, exec, ~/conf/hypr/script/screenshot.sh
bind = , PRINT, exec, grim -g "$(hyprctl monitors -j | jq -r '.[] | select(.focused) | "\(.x),\(.y) \(.width/2)x\(.height/2)"')"  -t ppm - | satty --filename -
