##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#windowrule = fullscreen, class:^(google-chrome)$,

# workspace = 20002, defaultFloat:true
# windowrulev = float, workspace:20002
# windowrulev = center, workspace:20002, floating:1

# windowrule = float, class:^(QQ)$

# windowrule = match:workspace name:qq, float on
# windowrule = match:workspace name:qq, maximize off
# windowrule = match:workspace name:qq, fullscreen off

windowrule = match:class QQ, float on
windowrule = match:class QQ, maximize off
windowrule = match:class QQ, fullscreen off
windowrule = match:class QQ, workspace name:qq

windowrule = match:class vlc, float on
windowrule = match:class vlc, maximize off
windowrule = match:class mpv, float on
windowrule = match:class mpv, maximize off

windowrule = match:class org.gnome.Nautilus, float on
windowrule = match:class org.gnome.Nautilus, maximize off

windowrule = match:class nm-connection-editor, float on
windowrule = match:class nm-connection-editor, maximize off

windowrule = match:class org.gnome.Loupe, float on
windowrule = match:class org.gnome.Loupe, maximize on
windowrule = match:class org.gnome.Loupe, fullscreen off

windowrule = match:title DevTools, match:class google-chrome, workspace name:devtools

windowrule = match:title DevTools, match:class google-chrome, workspace name:devtools
