#!/usr/bin/env bash

for i in $(seq 0 255); do
  # Print color code in a background and foreground color
  printf "\e[48;5;%dm\e[38;5;15m %03d " "$i" "$i"
  printf "\e[48;5;0m\e[38;5;%dm %03d\t" "$i" "$i"

  # Print newline to separate the color blocks
  if [ $((i + 1)) -le 16 ]; then
    [ $(( (i + 1) % 8 )) -eq 0 ] && printf "\n"
    [ $(( (i + 1) % 16 )) -eq 0 ] && printf "\n"
  else
    [ $(( ((i + 1) - 16) % 6 )) -eq 0 ] && printf "\n"
    [ $(( ((i + 1) - 16) % 36 )) -eq 0 ] && printf "\n"
  fi
done

printf "\e[033;00m\n"
